### ISSUE TITLE
Missing component

### ISSUE THREAD

**Issue by schkovich** [RyanGosden/TheTimesValidation#1]
I am getting: Failed to load resource: the server responded with a status of 500 (Internal Server Error) got URL http://www.staging.timesofmalta.com/bower_components/modernizr/modernizr.js

**Comment by RyanGosden** [comment]
Thanks 
I have now added the built (dist folder) and work (app folder).
Please add the dist folder to your test server to run or view the code files by viewing the app folder.

**Comment by schkovich** [comment]
Interesting decision. :wink: 

I would not place dist/ under source control. Same applies to node_modules/ and bower_components/.

Each team member should instead run bower and npm while build script should create distribution folder.
