### ISSUE TITLE
ReCaptcha

### ISSUE THREAD

**Issue by schkovich** [RyanGosden/TheTimesValidation#2]
For which domain ReCaptcha was configured?

![recaptcha](https://cloud.githubusercontent.com/assets/1050649/11397660/60bfbde0-937b-11e5-953d-0164c69ea81d.png)

**Comment by RyanGosden** [comment]
Domains listed is breadcrumbs.com.mt.
I also recently added timesofmalta.com so you will be able to test on your server.

Kindly note i have a bug where recaptcha is working on my localserver but not working on live server (http://breadcrumbs.com.mt/portfolio/tests/times/index.html) Working on this fix.

**Comment by schkovich** [comment]
good. it's working as far as i can see.
