### ISSUE TITLE
Form accept-charset attribute is not set

### ISSUE THREAD

**Issue by schkovich** [RyanGosden/TheTimesValidation#4]
[accept-charset](http://www.w3schools.com/tags/att_form_accept_charset.asp)

**Comment by RyanGosden** [comment]
Added accept-charset="ISO-8859-1" to form element.

**Comment by schkovich** [comment]
ha, you have to update it dynamically. [ISO/IEC_8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) for English and [ISO/IEC_8859-3](https://en.wikipedia.org/wiki/ISO/IEC_8859-3) for Maltese. Right? :smile:

**Comment by RyanGosden** [comment]
Thanks fully understand now :) charset & html lang attribute now changes dynamically.
